version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge 

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "8000:80"     
    environment:
      DB_CONNECTION_STRING: "Host=localhost;port=5432;database=blogdb;username=bloguser;password=bloguser"
    networks:
      - dockerapi-dev 

  postgres_image:
    image: postgres:latest
    ports:
     - 5432:5432
    restart: unless-stopped
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "bloguser"
      POSTGRES_PASSWORD: "bloguser"
      POSTGRES_DB: "blogdb"
    networks:
      - dockerapi-dev

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8050:80"
    networks:
      - dockerapi-dev

volumes:
  db_volume: