export const environmentPermisos = {
    //GESTORDOCUMENTAL
    GESTORDOCUMENTAL_BANDEJA_ENTRADA: 532,
    GESTORDOCUMENTAL_REGISTRO: 756,
    GESTORDOCUMENTAL_BUSQUEDA: 725,
  
    //OFICINAPARTES
    OFICINAPARTES_BUSQUEDA: 788,
    OFICINAPARTES_REGISTRO: 757,

  
    //RRHH
    RRHH_INGRESO_DESEMP: 773,
    RRHH_VALIDAR_DESEMPE: 772,
    RRHH_LISTA_FUNCIONARIOS: 771,
    RRHH_LISTA_JEFATURAS: 773,
    RRHH_PREINFORME: 776,
  
    //CODIGOMEDICO
    CODIGOMEDICO_SOLICITUD_PAGE : 780,
    CODIGOMEDICO_PENDIENTES_POR_SERVICIO : 795,
    CODIGOMEDICO_INGRESARSOLICITUD_PAGE: 796,
    CODIGOMEDICO_SOLICITUD : 780,
    CODIGOMEDICO_PENDIENTES : 782,
  }