export interface Sabst030Usuario {
    codigo:         number;
    rut:            number;
    codusuario:     string;
    digitover:      string;
    apellpat:       string;
    apellmat:       string;
    nombres:        string;
    nombre2:        string;
    razsocial:      string;
    tipo:           number;
    direccion:      string;
    emisorcred:     number;
    comuna:         number;
    fono:           string;
    fax:            null;
    prevision:      number;
    funcionario:    number;
    estado:         number;
    fecha:          string;
    atencpac:       number;
    diagnost:       number;
    datreser:       number;
    estsalud:       number;
    observacion:    number;
    catfarmacia:    number;
    retorno:        boolean;
    identificacion: null;
    servicio:       null;
    empresa:        null;
    mes:            null;
    año:            null;
    calidad:        null;
    vigencia:       null;
    TipoUsuario     : number;
}
